### ISSUE TITLE
 Add required checks to repository settings

### ISSUE THREAD

**Issue by papotte** [lisbethpurrucker/quouch#51]
GitHub has very useful tools to prevent faulty commits from making it into main.

Let's configure them, since now we have actions running.

Read more:
- [Protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)
- [More about automation](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/best-practices-for-projects#use-automation)
- [More about security on GitHub](https://www.legitsecurity.com/blog/github-security-best-practices-your-team-should-be-following)

**Comment by lisbethpurrucker** [comment]
Done!
